# Generated by Django 5.0.6 on 2024-05-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='نام دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='نام کتاب')),
                ('Author', models.CharField(max_length=150, verbose_name='نویسنده')),
                ('publisher', models.CharField(max_length=150, verbose_name='انتشارات')),
                ('isBorrowing', models.BooleanField(default=False, verbose_name='قرض گرفته شده؟')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.category', verbose_name='دسته بندی')),
            ],
        ),
    ]
