# Generated by Django 5.0.6 on 2024-05-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='نام نقش')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='نام عضو')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('libId', models.IntegerField(verbose_name='شماره عضویت کتابخانه')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character', verbose_name='نقش')),
            ],
        ),
    ]
